variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndDeploy
  pool:
    name: Default
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'BullMoneyServiceConnectionToAzureAppRegistration'
      appType: 'webAppLinux'
      appName: 'bullmoney'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
